package com.example.FinancialGroup.enums;

public enum StatusMessage {
    NOT_FOUND,
    BAD_REQUEST,
    DELETED,
    INTERNAL_SERVER_ERROR,
    UN_AUTHORIZED,
    LENGTH_REQUIRED,
    BAD_CREDENTAILS,
    ALREADY_EXISTS,
    FORMAT_NOT_SUPPORTED,
    MANDATORY_EXPECTED,
    CONFLICT,

    CREATED,
    SUCCESS,
    INVALID_NUMBER_OF_TRAILS,
    IS_EXPIRED,
    SECURITY_ISSUE,
}
